lamp:
  database:
    multiTenantType: COLUMN
  druid:
    username: 'root'
    password: 'root'
    # 生产使用原生驱动，开发使用p6spy驱动打印日志
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lamp_activiti?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true

springdoc:
  group-configs:
    - group: 'activiti_act'
      displayName: '流程组件模块'
      paths-to-match: '/**'
      packages-to-scan: top.tangyh.lamp.activiti.controller



spring:
  freemarker:
    suffix: .ftl
    cache: false
    charset: UTF-8
    contentType: text/html
    requestContextAttribute: ctx
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/
    settings:
      defaultEncoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
  activiti:
    database-schema-update: true
    async-executor-activate: false
    history-level: FULL
    check-process-definitions: false

server:
  port: 8779

setting:
  path:
    uploadPath: /data/projects/uploadfile/temp/
